=== Robbie1977/org.geppetto.simulation/src/main/resources/schema/simulationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openworm.org/simulationSchema"
	xmlns:tns="http://www.openworm.org/simulationSchema"
	elementFormDefault="qualified">



	<complexType name="Configuration">
		<sequence>
			<element name="outputFormat" type="tns:OutputFormat"></element>
		</sequence>
	</complexType>

	<complexType name="Aspect">
		<sequence>
			<element name="modelInterpreter" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="modelURL" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="simulator" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="id" type="string" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>

	<simpleType name="OutputFormat">
		<restriction base="string">
			<enumeration value="RAW" />
			<enumeration value="THREEJSON" />
		</restriction>
	</simpleType>

	<element name="simulation">
		<complexType>
			<sequence>
				<element name="configuration" type="tns:Configuration"
					maxOccurs="1" minOccurs="1"></element>
				<element name="aspects" type="tns:Aspect" maxOccurs="unbounded"
					minOccurs="1"></element>
				<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
			</sequence>
		</complexType>
	</element>
	
</schema>

=== Robbie1977/org.geppetto.simulation/test/simulation/sim-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:simulation xmlns:tns="http://www.example.org/simulationSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/simulationSchema ../../src/main/resources/schema/simulationSchema.xsd ">
  <tns:configuration>
    <tns:outputFormat>RAW</tns:outputFormat>
  </tns:configuration>
  <tns:aspects>
    <tns:modelInterpreter>sphModelInterpreter</tns:modelInterpreter>
    <tns:modelURL>someurl</tns:modelURL>
    <tns:simulator>sphSimulator</tns:simulator>
    <tns:id>sph</tns:id>
  </tns:aspects>
  <tns:name>sph</tns:name>
</tns:simulation>
